AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  GoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: provided.al2
      Handler: bootstrap
      Architectures:
        - arm64
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - "*"
          AllowHeaders:
            - "*"

Outputs:
  LambdaUrl:
    Description: "Lambda Function URL"
    Value: !GetAtt GoLambdaFunction.FunctionUrl